steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/cicd-system-demo-01/cicd-demo-01/whereami', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/cicd-system-demo-01/cicd-demo-01/whereami']
images: ['us-central1-docker.pkg.dev/cicd-system-demo-01/cicd-demo-01/whereami']